/* Automatically generated by "build-radpaths-h" */
#define RACINE      (getenv("RAD_RACINE"))
#define LOGDIR		"/hss_freeradius/x86/var/log/radius"
#define LIBDIR		"/hss_freeradius/x86/lib"
#define RADDBDIR	"/hss_freeradius/x86/etc/raddb"
#define RUNDIR		"/hss_freeradius/x86/var/run"
#define SBINDIR		"/hss_freeradius/x86/sbin"
#define RADIR		"/hss_freeradius/x86/var/log/radius/radacct"
