#
#	$Id: Makefile,v 1.2 2000/02/28 22:16:38 aland Exp $
#

TARGET		= rlm_realm
SRCS		= rlm_realm.c
HEADERS		=
RLM_CFLAGS	=
RLM_LIBS	=

# over-ride the previous assignment if we're not building anything
include ../rules.mak

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)

